name = "STRELA"
uuid = "c1a2adf5-a52e-430c-84bf-168fab86e0c1"
authors = ["Damir Akchurin"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
