# Refer to https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates for details.
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"